language: python
dist: bionic

python:
  - 3.6
  - 3.7
  - 3.8

stages:
  - lint
  - test

before_script:
  - pip install ansible
  - ansible-galaxy install pacifica.ansible_pacifica pacifica.ansible_travis
  - ansible-playbook ~/.ansible/roles/pacifica.ansible_travis/molecule/common/playbook.yml -i ~/.ansible/roles/pacifica.ansible_travis/molecule/common/inventory.yml -e "ansible_python_interpreter=/home/travis/virtualenv/python${TRAVIS_PYTHON_VERSION}/bin/python travis_virtualenv=python${TRAVIS_PYTHON_VERSION} github_repository=dispatcher"
  - |
    curl -X PUT -H 'Last-Modified: Sun, 06 Nov 1994 08:49:37 GMT' --upload-file README.md http://127.0.0.1:8080/103
    curl -X PUT -H 'Last-Modified: Sun, 06 Nov 1994 08:49:37 GMT' --upload-file README.md http://127.0.0.1:8080/104
    readme_size=$(stat -c '%s' README.md)
    readme_sha1=$(sha1sum README.md | awk '{ print $1 }')
    echo '{ "hashsum": "'$readme_sha1'", "hashtype": "sha1", "size": '$readme_size'}' > /tmp/file-104-update.json
    curl -X POST -H 'content-type: application/json' -T /tmp/file-104-update.json 'http://localhost:8121/files?_id=103'
    curl -X POST -H 'content-type: application/json' -T /tmp/file-104-update.json 'http://localhost:8121/files?_id=104'
  - curl 'http://127.0.0.1:8051/getid?range=200&mode=file'
  - printf 'http://localhost:8066/upload\nhttp://localhost:8066/get_state\nhttp://localhost:8181/uploader\nhttp://localhost:8181/ingest\nhttp://localhost:8081\nhttp://localhost:8181/status/transactions/by_id\nTrue\nNone\n' | pacifica-cli configure
script:
  - pip install .
  - cd tests
  - coverage run --include='*/pacifica/dispatcher_k8s/*' -m pytest -xsv
  - coverage report -m --fail-under 100

jobs:
  include:
    - stage: lint
      python: 3.6
      script: pre-commit run -a
    - python: 3.7
      script: pre-commit run -a
    - python: 3.8
      script: pre-commit run -a

install:
- pip install .
- pip install -r requirements-dev.txt
